### PR TITLE
Write to disk

### PR DESCRIPTION
**Pull request by mintukurmi**
Added:
-  types saved to a file.
-  custom output file to save types.
-  option to print types to the console.

I have updated the readme file as well.

Please review the PR and merge.
Thanks.

### CODE REVIEW

**Comment by deanc** [comment]
Hi!

What value does this add over just piping to disk? e.g. `kysely-schema-generator > /path/to/output.ts`

**Comment by mintukurmi** [comment]
Hi @deanc , 
Saving generated types to an output file is an optional feature. It is for users who want to keep a copy of the generated types in their project folder. If somebody doesn't want to use the feature, there is no issue they will not provide the ` -o file-path` attribute. Then the generated types will be stored inside of `node_modules` under the package exporting the ` interface DB` for the user to use directly.

Currently, types are not printed by default. The current default behavior is that the types will be generated and stored inside the package and an` interface DB` will be exported. Types will only be printed if` --print` is passed.

**Comment by deanc** [comment]
As I said in the previous comment, you can just pipe the output using > with any shell to a file.

Types are printed by default, and if you are not getting that behaviour then it's either a bug or some issue your end.

**Comment by mintukurmi** [comment]
Piping to disk and writing to a file has a kind of similar behavior. But, the former is simple to use and straightforward. While the latter gives more control, like formatting, doing some kind of manipulation, etc. 

Since we are capturing the generated types by default. I think console logging the types by default makes no sense unless the user wants to by providing a flag like `--print`

**Comment by deanc** [comment]
@mintukurmi I'm afraid we'll have to agree to disagree here. One of the benefits of console.log'ing the types straight to the shell is that you can do whatever you want to it with your shell of choice. You can write to disk or just have a look. This PR just adds an un-necessary layer of complexity to functionality you get for free from your shell.

**Pull request closed without merging**
