### PR TITLE
Fixed: TypeError with mysql:8.0.35 and up

### PR DESCRIPTION
**Pull request by mintukurmi**
Fixed TypeError,  which it throws when tested with mysql:8.0.35 and 8.2.0.

Here is the error:
```
$ node dist/index.js 
D:\Practice\kysely-schema-generator\dist\src\db.js:30
    const createTable = yield db.raw(`SHOW CREATE TABLE ${tableName.replace(/[^\w]+/i, "")}`);
                                                                    ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at D:\Practice\kysely-schema-generator\dist\src\db.js:30:69
    at Generator.next (<anonymous>)
    at D:\Practice\kysely-schema-generator\dist\src\db.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Practice\kysely-schema-generator\dist\src\db.js:4:12)
    at getCreateTableStatement (D:\Practice\kysely-schema-generator\dist\src\db.js:29:52)
    at D:\Practice\kysely-schema-generator\dist\index.js:35:114
    at Array.map (<anonymous>)
    at Command.<anonymous> (D:\Practice\kysely-schema-generator\dist\index.js:35:62)
    at Generator.next (<anonymous>)

Node.js v20.9.0
```
The issue is in the recent versions of MySQL, the column name is `TABLE_NAME `(instead of `table_name`) in the `information_schema` table.

So I am adding the fix, with this.

### CODE REVIEW

**Comment by deanc** [comment]
I'm not sure I quite understand, you're aliasing the field name with the same field name? I see no reference to case in the PR? Also please can you remove the node version change.

**Comment by mintukurmi** [comment]
If we add  `console.log({tables})`  after  Line 22 and run the index file (Refer to `index.ts:22`), we'll get output, for example:
` { tables: [ { TABLE_NAME: 'posts' }, { TABLE_NAME: 'users' } ] } `

If we add  console.log({ tableNames }) after line 27. we'll get output,
`{ tableNames: [ undefined, undefined ] }`

So, by aliasing the column, we can make sure that the column name is always consistent ( i.e table_name ).

Considering the above example we'll get,
` { tables: [ { table_name: 'posts' }, { table_name: 'users' } ] } ` and  `{ tableNames: [ posts, users] } `
And it throws no error.

**Comment by mintukurmi** [comment]
Also, I have removed the node types as well.

**Comment by deanc** [comment]
Thanks @mintukurmi - last thing - why is github showing this up as a diff of the whole file now?

**Comment by mintukurmi** [comment]
Maybe it's an issue of git. But I see both files are identical.

**Pull request merged**
